### ISSUE TITLE
emby 紫罗兰永恒花园 同步失败

### ISSUE THREAD

**Issue by LINKlang** [SanaeMio/Bangumi-syncer#28]
已在config配置id
日志
```
[11/29/24 19:42:24.1] 接收到同步请求：media_type='episode' title='紫罗兰永恒花园' ori_title=' ' season=1 episode=1 release_date='2018-01-10' user_name='Desktop'
[11/29/24 19:42:25.0] bgm: 紫罗兰永恒花园 S01E1 已看过，不再重复标记
INFO:     127.0.0.1:56088 - "POST /Emby HTTP/1.1" 200 OK
INFO:     127.0.0.1:56100 - "POST /Emby HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bangumi-syncer\bangumi_sync.py", line 157, in emby_sync
    "release_date": emby_data["Item"]["PremiereDate"][:10],
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'PremiereDate'
INFO:     127.0.0.1:56104 - "POST /Emby HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bangumi-syncer\bangumi_sync.py", line 157, in emby_sync
    "release_date": emby_data["Item"]["PremiereDate"][:10],
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'PremiereDate'
```

**Comment by SanaeMio** [comment]
估计是Emby通知字段有变化
麻烦先在config.ini配置中将debug改为True，再同步一次上面报错这一集，贴下日志中“接收到Emby同步请求”后面的内容，谢谢~

**Comment by LINKlang** [comment]
> 估计是Emby通知字段有变化 麻烦先在config.ini配置中将debug改为True，重启程序后再同步一次上面报错这一集，贴下日志中“接收到Emby同步请求”后面的内容，谢谢~

非常感谢回复，以下是log
```
INFO:     127.0.0.1:65139 - "POST /Emby HTTP/1.1" 200 OK
[12/02/24 21:08:18.4] 接收到Emby同步请求：{'Title': 'item.markplayed', 'Date': '2024-12-02T10:08:16.3357846Z', 'Event': 'item.markplayed', 'User': {'Name': 'Desktop', 'Id': 'df512e4f0b814d0ab2b2b0e0229569b1'}, 'Item': {'Name': '“我爱你”与自动手记人偶', 'OriginalTitle': '「愛してる」と自動手記人形', 'ServerId': 'b7333cd0a42c4179a9db2df0fb1b5853', 'Id': '12745', 'DateCreated': '2024-09-30T07:34:59.0000000Z', 'Container': 'mkv', 'SortName': '“我爱你”与自动手记人偶', 'PremiereDate': '2018-01-10T13:00:00.0000000Z', 'ExternalUrls': [{'Name': 'IMDb', 'Url': 'https://www.imdb.com/title/tt7225072'}, {'Name': 'TheTVDB', 'Url': 'https://thetvdb.com/?tab=episode&id=6135427'}, {'Name': 'Trakt', 'Url': 'https://trakt.tv/search/tmdb/1395818?id_type=episode'}], 'Path': 'D:\\Anime\\TV Shows\\[subbers] Violet Evergarden [BDRip 4K-upconv]\\Menus\\[subbers] Violet Evergarden - Vol.01 Theater Ver. [BDRip HEVC FLAC].mkv', 'Overview': '有一个没有感情的少女。少女为了战 斗而活着。名字是薇尔莉特·伊芙加登。残酷的战争结束了，新的时代即将开始。在战场上受伤的薇尔莉特在床上醒来。洁白光滑的双臂 ，被银色闪耀的假手代替。她残缺的身体，战争的记忆和上司“基尔伯特·布甘比利亚”最后告诉自己的话。但是，这句话的意义薇尔莉特·伊芙加登无法理解。一个男人出现在那里。原陆军中校的克劳迪亚·霍金斯来接她，二人前往的是在南部的港口城市莱顿。充满活力的人 们，美丽的港口的风景，莱顿的街道迎接薇尔莉特·伊芙加登。在新的城市薇尔莉特与“自动手记人偶”的相遇。那是把委托人的心情被代 替语言写在信上的工作。有时委托人就连藏在心中的想法也可以猜到。基尔伯特的话“我爱你”，如果成为“自动手记人偶”的话，也许会明白那个意思。想知道“我爱你”。这是为了感情不是为了战斗的“工具”生活的薇尔莉特·伊芙加登，第一次表明了自己的意志。', 'Taglines': [], 'Genres': [], 'CommunityRating': 7.6, 'RunTimeTicks': 564750000, 'Size': 57599369, 'FileName': '[subbers] Violet Evergarden - Vol.01 Theater Ver. [BDRip HEVC FLAC].mkv', 'Bitrate': 8159273, 'ProductionYear': 2018, 'IndexNumber': 1, 'ParentIndexNumber': 1, 'RemoteTrailers': [], 'ProviderIds': {'Imdb': 'tt7225072', 'Tvdb': '6135427', 'Tmdb': '1395818', 'official website': 'http://tv.violet-evergarden.jp/story/#01'}, 'IsFolder': False, 'ParentId': '12729', 'Type': 'Episode', 'Studios': [{'Name': 'Tokyo MX', 'Id': 11700}, {'Name': 'Kyoto Animation', 'Id': 9721}, {'Name': 'Pony Canyon', 'Id': 9843}, {'Name': 'ABC Animation', 'Id': 9844}, {'Name': 'Lantis', 'Id': 9845}, {'Name': 'Miracle Bus', 'Id': 9846}], 'GenreItems': [], 'TagItems': [], 'ParentLogoItemId': '12500', 'ParentBackdropItemId': '12500', 'ParentBackdropImageTags': ['2387b49ab07680f12c596de121ca06d7'], 'UserData': {'PlaybackPositionTicks': 0, 'PlayCount': 1, 'IsFavorite': False, 'LastPlayedDate': '2024-12-02T10:08:16.0000000Z', 'Played': True}, 'SeriesName': '紫罗兰永恒花园', 'SeriesId': '12500', 'SeasonId': '12729', 'PrimaryImageAspectRatio': 1.7777777777777777, 'SeriesPrimaryImageTag': '4ab141d990452b8d3bc6f93e15d572e1', 'SeasonName': 'Menus', 'ImageTags': {'Primary': 'a704e7769a6ea59d7fd389ea5ab778e1'}, 'BackdropImageTags': [], 'ParentLogoImageTag': '919462443f8714f621b20472038e7cec', 'MediaType': 'Video', 'Width': 1920, 'Height': 1080}, 'Server': {'Name': 'DESKTOP-JR1OH2L', 'Id': 'b7333cd0a42c4179a9db2df0fb1b5853', 'Version': '4.8.10.0'}}
[12/02/24 21:08:18.4] 重新组装 JSON 报文：{'media_type': 'episode', 'title': '紫罗兰永恒花园', 'ori_title': ' ', 'season': 1, 'episode': 1, 'release_date': '2018-01-10', 'user_name': 'Desktop'}
[12/02/24 21:08:18.4] 接收到同步请求：media_type='episode' title='紫罗兰永恒花园' ori_title=' ' season=1 episode=1 release_date='2018-01-10' user_name='Desktop'
[12/02/24 21:08:18.4] 匹配到自定义映射：紫罗兰永恒花园=183878
[12/02/24 21:08:18.7] bgm: 查询到 紫罗兰永恒花园 (https://bgm.tv/subject/183878) S01E1 (https://bgm.tv/ep/730523)
[12/02/24 21:08:19.3] {'episode': {'airdate': '2018-01-10', 'name': '「愛してる」と自動手記人形', 'name_cn': '“爱”与自动手记人偶', 'duration': '00:24:00', 'desc': '脚本：吉田玲子\u3000絵コンテ：石立太一\u3000演出：石立太一、藤田春香、澤 真 平\r\n作画監督：丸木宣明、高瀬亜貴子、明見裕子、丸子達就\r\n\r\n感情を持たない一人の少女がいた。\r\n少女は戦うための「道具」として生きていた。\r\n名はヴァイオレット。\r\n\r\n時は流れ戦争は終わり、新たな時代が始まろうとしていた。\r\n戦地で傷ついたヴァイレットはベッドの上で目を覚ます。\r\n白くなめらかな両腕は、砲弾を受け銀色に輝く義手に替わっていた。\r\n彼女に残されたものは、戦場の記憶と上官〈ギルベルト・ブーゲンビリア少佐〉が\r\n最後に告げた言葉だけ。\r\nだが、その言葉の意味をヴァイオレットは理解できずにいた。\r\n\r\nそこへ、一人の男が現れる。元陸軍中佐のクラウディア・ホッジンズ。\r\nホッジンズはギルベルトに代わって彼女を迎えに来たと言う。\r\n二人が向かうのは南部の港町・ライデンシャフトリヒの首都、ライデン。\r\n活気あふれる人々、美しい港の風景、ライデンの街はヴァイオレットを迎え入れる。\r\n\r\n新しい街でヴァイオレットは「自動手記人形」に出会う。\r\nそれは、依頼主の気持ちを言葉に代えて手紙に綴る仕事。\r\n時には依頼主が胸のうちに秘めた想いさえもすくい取る。\r\n\r\nギルベルトがヴァイオレットに残した言葉―――「愛してる」\r\n「自動手記人形」になればその意味がわかるかも知 れない。\r\n\r\n――「愛してる」が知りたいのです。――\r\n\r\nそれは、感情を持たず戦うための「道具」として生きてきたヴァイオレットが、\r\n初めて示した意志だった。', 'ep': 1, 'sort': 1, 'id': 730523, 'subject_id': 183878, 'comment': 429, 'type': 0, 'disc': 0, 'duration_seconds': 1440}, 'type': 2}
[12/02/24 21:08:19.3] bgm: 紫罗兰永恒花园 S01E1 已看过，不再重复标记
INFO:     127.0.0.1:65284 - "POST /Emby HTTP/1.1" 200 OK
[12/02/24 21:08:21.4] 接收到Emby同步请求：{'Title': 'item.markplayed', 'Date': '2024-12-02T10:08:16.3362167Z', 'Event': 'item.markplayed', 'User': {'Name': 'Desktop', 'Id': 'df512e4f0b814d0ab2b2b0e0229569b1'}, 'Item': {'Name': '“我爱你”与自动手记人偶', 'ServerId': 'b7333cd0a42c4179a9db2df0fb1b5853', 'Id': '12746', 'DateCreated': '0001-01-01T00:00:00.0000000Z', 'Container': 'mkv', 'SortName': '“我爱你”与自动手记人偶', 'ExternalUrls': [], 'Path': 'D:\\Anime\\TV Shows\\[subbers] Violet Evergarden [BDRip 4K-upconv]\\Menus\\[subbers] Violet Evergarden - Vol.01 [BDRip HEVC FLAC].mkv', 'Taglines': [], 'Genres': [], 'RunTimeTicks': 564750000, 'Size': 57132387, 'FileName': '[subbers] Violet Evergarden - Vol.01 [BDRip HEVC FLAC].mkv', 'Bitrate': 8093122, 'IndexNumber': 1, 'ParentIndexNumber': 1, 'RemoteTrailers': [], 'ProviderIds': {}, 'IsFolder': False, 'ParentId': '12729', 'Type': 'Episode', 'Studios': [{'Name': 'Tokyo MX', 'Id': 11700}, {'Name': 'Kyoto Animation', 'Id': 9721}, {'Name': 'Pony Canyon', 'Id': 9843}, {'Name': 'ABC Animation', 'Id': 9844}, {'Name': 'Lantis', 'Id': 9845}, {'Name': 'Miracle Bus', 'Id': 9846}], 'GenreItems': [], 'TagItems': [], 'ParentLogoItemId': '12500', 'ParentBackdropItemId': '12500', 'ParentBackdropImageTags': ['2387b49ab07680f12c596de121ca06d7'], 'UserData': {'PlaybackPositionTicks': 0, 'PlayCount': 1, 'IsFavorite': False, 'LastPlayedDate': '2024-12-02T10:08:16.0000000Z', 'Played': True}, 'SeriesName': '紫罗兰永恒花园', 'SeriesId': '12500', 'SeasonId': '12729', 'SeriesPrimaryImageTag': '4ab141d990452b8d3bc6f93e15d572e1', 'SeasonName': 'Menus', 'ImageTags': {}, 'BackdropImageTags': [], 'ParentLogoImageTag': '919462443f8714f621b20472038e7cec', 'MediaType': 'Video'}, 'Server': {'Name': 'DESKTOP-JR1OH2L', 'Id': 'b7333cd0a42c4179a9db2df0fb1b5853', 'Version': '4.8.10.0'}}
INFO:     127.0.0.1:65297 - "POST /Emby HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\protocols\http\httptools_impl.py", line 409, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.scope, self.receive, self.send
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\uvicorn\middleware\proxy_headers.py", line 60, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\applications.py", line 113, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\errors.py", line 187, in __call__
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\errors.py", line 165, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\middleware\exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 715, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 735, in app
    await route.handle(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 288, in handle
    await self.app(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 76, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\starlette\routing.py", line 73, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 301, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "C:\Users\31857\AppData\Local\Programs\Python\Python313\Lib\site-packages\fastapi\routing.py", line 212, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Bangumi-syncer\bangumi_sync.py", line 157, in emby_sync
    "release_date": emby_data["Item"]["PremiereDate"][:10],
                    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'PremiereDate'
```

**Comment by SanaeMio** [comment]
问题倒是已经清楚了，应该是您看的BD(原盘？)所以emby送过来的信息不完整导致的，如果是正常的分集（比如VCB等压制组的非原盘格式资源）应该不存在这个情况。
因为最近有了宝宝，短期内可能没太有机会来修复这个问题，不好意思。

**Comment by LINKlang** [comment]
> 问题倒是已经清楚了，应该是您看的BD(原盘？)所以emby送过来的信息不完整导致的，如果是正常的分集（比如VCB等压制组的非原盘格式资源）应该不存在这个情况。 因为最近有了宝宝，短期内可能没太有机会来修复这个问题，不好意思。

首先恭喜一下作者您，
目前这个问题我已经自适应了，作者还是先处理生活上的事吧
